# Generated by Django 6.0.4 on 2026-05-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
