# Generated by Django 6.0.4 on 2026-05-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
