# Generated by Django 6.0.4 on 2026-05-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0004_alter_product_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='variant_name',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='weight',
        ),
    ]
