# Generated by Django 6.0.4 on 2026-05-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_products', '0005_remove_product_base_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'color', 'size')},
        ),
    ]
