# Generated by Django 6.0.4 on 2026-05-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_products", "0006_alter_variant_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
