# Generated by Django 6.0.4 on 2026-06-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_review_options_alter_review_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="show_message",
            field=models.BooleanField(default=False),
        ),
    ]
