# Generated by Django 6.0.4 on 2026-06-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_referral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralreward',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
