# Generated by Django 6.0.4 on 2026-06-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_referralreward_is_seen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralreward",
            name="is_seen",
        ),
    ]
