# Generated by Django 6.0.4 on 2026-05-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_orders", "0011_order_show_status_message_order_status_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash On Delivery"),
                    ("RAZORPAY", "Razorpay"),
                    ("WALLET", "Wallet"),
                ],
                default="COD",
                max_length=20,
            ),
        ),
    ]
