# Generated by Django 6.0.4 on 2026-06-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_orders', '0013_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
    ]
