# Generated by Django 6.0.4 on 2026-06-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_orders", "0014_order_refund_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="offer_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="offer_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
