# Generated by Django 6.0.4 on 2026-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_orders', '0015_orderitem_offer_discount_orderitem_offer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
