# Generated by Django 6.0.4 on 2026-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressinfo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(default="", max_length=50),
        ),
    ]
