# Generated by Django 6.0.4 on 2026-04-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userinfo", "0003_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
